[buildPlans.recursivka-mono]
family = "Recursivka Mono"
spacing = "normal"
serifs = "sans"
no-cv-ss = true
export-glyph-names = true

  [buildPlans.recursivka-mono.variants]
  inherits = "ss17"

    [buildPlans.recursivka-mono.variants.design]
    capital-a = "straight-top-serifed"
    capital-c = "unilateral-inward-serifed"
    capital-g = "toothed-inward-serifed-capped"
    capital-h = "top-left-serifed"
    capital-i = "short-serifed"
    capital-j = "serifed"
    capital-k = "straight-bottom-right-serifed"
    capital-m = "hanging-motion-serifed"
    capital-n = "motion-serifed"
    capital-q = "crossing"
    capital-r = "straight-open-motion-serifed"
    capital-t = "motion-serifed"
    capital-u = "motion-serifed"
    capital-v = "straight-motion-serifed"
    capital-w = "straight-motion-serifed"
    capital-x = "straight-motion-serifed"
    capital-y = "straight-motion-serifed"
    capital-z = "straight-serifless"
    a = "double-storey-tailed"
    f = "flat-hook-tailed"
    g = "double-storey"
    h = "straight-motion-serifed"
    i = "hooky"
    k = "curly-top-left-serifed"
    l = "tailed"
    m = "short-leg-top-left-serifed"
    n = "straight-top-left-serifed"
    q = "earless-corner-tailed"
    r = "serifless"
    s = "serifless"
    t = "flat-hook"
    u = "toothed"
    x = "straight-serifless"
    y = "cursive-flat-hook-motion-serifed"
    z = "straight-serifless"
    zero = "dotted"
    one = "no-base"
    two = "curly-neck"
    three = "flat-top"
    four = "semi-open"
    five = "oblique-upper-left-bar"
    six = "open-contour"
    seven = "bend-crossbar"
    eight = "two-circles"
    nine = "open-contour"
    punctuation-dot = "square"
    asterisk = "hex-low"
    underscore = "high"
    caret = "medium"
    paren = "flat-arc"
    brace = "curly-flat-boundary"
    number-sign = "upright"
    at = "fourfold"
    dollar = "open-cap"
    percent = "rings-continuous-slash"
    bar = "natural-slope"
    ascii-single-quote = "straight"
    ascii-grave = "straight"
    question = "corner"
    pilcrow = "high"
    cent = "open"
    lig-ltgteq = "slanted"
    lig-neq = "slightly-slanted"
    lig-equal-chain = "with-notch"
    lig-hyphen-chain = "with-notch"
    lig-double-arrow-bar = "without-notch"
    lig-single-arrow-bar = "without-notch"

  [buildPlans.recursivka-mono.ligations]
  inherits = "javascript"

[buildPlans.recursivka-mono.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.recursivka]
family = "Recursivka"
spacing = "quasi-proportional"
serifs = "sans"
no-cv-ss = true
export-glyph-names = true

  [buildPlans.recursivka.variants]
  inherits = "ss17"

    [buildPlans.recursivka.variants.design]
    capital-a = "straight-top-serifed"
    capital-c = "unilateral-inward-serifed"
    capital-g = "toothed-inward-serifed-capped"
    capital-h = "top-left-serifed"
    capital-i = "short-serifed"
    capital-j = "serifed"
    capital-k = "straight-bottom-right-serifed"
    capital-m = "hanging-motion-serifed"
    capital-n = "motion-serifed"
    capital-q = "crossing"
    capital-r = "straight-open-motion-serifed"
    capital-t = "motion-serifed"
    capital-u = "motion-serifed"
    capital-v = "straight-motion-serifed"
    capital-w = "straight-motion-serifed"
    capital-x = "straight-motion-serifed"
    capital-y = "straight-motion-serifed"
    capital-z = "straight-serifless"
    a = "double-storey-tailed"
    f = "flat-hook-tailed"
    g = "double-storey"
    h = "straight-motion-serifed"
    i = "hooky"
    k = "curly-top-left-serifed"
    l = "tailed"
    m = "short-leg-top-left-serifed"
    n = "straight-top-left-serifed"
    q = "earless-corner-tailed"
    r = "serifless"
    s = "serifless"
    t = "flat-hook"
    u = "toothed"
    x = "straight-serifless"
    y = "cursive-flat-hook-motion-serifed"
    z = "straight-serifless"
    zero = "dotted"
    one = "no-base"
    two = "curly-neck"
    three = "flat-top"
    four = "semi-open"
    five = "oblique-upper-left-bar"
    six = "open-contour"
    seven = "bend-crossbar"
    eight = "two-circles"
    nine = "open-contour"
    punctuation-dot = "square"
    asterisk = "hex-low"
    underscore = "high"
    caret = "medium"
    paren = "flat-arc"
    brace = "curly-flat-boundary"
    number-sign = "upright"
    at = "fourfold"
    dollar = "open-cap"
    percent = "rings-continuous-slash"
    bar = "natural-slope"
    ascii-single-quote = "straight"
    ascii-grave = "straight"
    question = "corner"
    pilcrow = "high"
    cent = "open"
    lig-ltgteq = "slanted"
    lig-neq = "slightly-slanted"
    lig-equal-chain = "with-notch"
    lig-hyphen-chain = "with-notch"
    lig-double-arrow-bar = "without-notch"
    lig-single-arrow-bar = "without-notch"

  [buildPlans.recursivka.ligations]
  inherits = "javascript"

[buildPlans.recursivka.widths.normal]
shape = 600
menu = 5
css = "normal"
